const STATUS_OK = 200;
const STATUS_CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 500;
const NOT_AUTHORIZED = 403;

module.exports = {
  STATUS_OK, STATUS_CREATED, BAD_REQUEST, NOT_FOUND, METHOD_NOT_ALLOWED, NOT_AUTHORIZED,
};
